version: '3.8'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:16.2-alpine3.19
    build:
      dockerfile: Dockerfile.db
      context: .
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend_network
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nest-backend:
    container_name: nest-backend
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - ${PORT}:${PORT}
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend_network
    volumes:
      - ./src:/app/src
    restart: always
    depends_on:
      - postgres-db

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:




# version: '3'
# services:

#   postgres:
#     image: "postgres:14.5"
#     ports:
#       - ${POSTGRES_PORT}:${POSTGRES_PORT}
#     environment:
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_PORT: ${POSTGRES_PORT}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}

